# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               André Torres
tagline:             'logger.debug("welcome")'
description:         'I''m a software developer from Brazil who builds stuff and share about it.'
url:                 http://andre2w.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              André Torres
  url:               https://twitter.com/lnk2w
  email:             andre2w@gmail.com

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate